name: sea_battle
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: 4.15.5
  collection: 1.18.0
  cupertino_icons: 1.0.2
  equatable: 2.0.5
  firebase_auth: 4.17.5
  firebase_core: 2.25.4
  form_builder_validators: 9.1.0
  flutter_bloc: 8.1.4
  flutter_form_builder: 9.2.1
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1
  json_serializable: 6.7.1
  boilerplate_annotations:
  json_annotation: 4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  boilerplate_generators:
  build_runner: 2.4.8
  flutter_gen_runner: 5.4.0
  flutter_lints: 3.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf

flutter_gen:
output: lib/gen/
